server:
  port: 0

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:tcp://localhost/~/orderdb #최초 웹콘솔에서 jdbc url=>jdbc:h2:~/orderdb 연결(연결시험은오류남) 한 번 수행하고 로그아웃 후 왼쪽 url 입력 후 시작
    username: sa
    password:
    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka